upstream main-service{
    least_conn;
    server ping-main:8000 max_fails=8 fail_timeout=10s;
}

upstream cm-service{
    least_conn;
    server ping-cm:8001 max_fails=8 fail_timeout=10s;
}

server {
    listen 80;
    location / {
        return 301 /ping/;
    }

    location /ping/ {
        # root appends the entire URI for final search directory
        # /ping/images => /usr/share/nginx/html/ping/images
        # alias removes the matched prefix
        # /ping/images => /usr/share/nginx/html/images
        alias /usr/share/nginx/html/;

        # index states exact file to serve inside the reached directory
        index index.html;

        # try_files checks for existence of files in order and serves the first match
        # if no match, internally redirects to the last URI (without changing URL in browser)
        try_files $uri $uri/ /ping/index.html;
    }

    location /main_service/ {
        proxy_pass http://main-service;
    }

    location /cm_service/ {
        proxy_pass http://cm-service;
        
        # Websocket specific directives
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        # Maybe required for logging and debugging
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}