name: Ci?CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  # ---------------------------------------------------
  # PHASE 1: Run Integration Tests
  # ---------------------------------------------------
  test:
    runs-on: ubuntu-latest
      # Inject dummy environment variables so the app boots successfully in CI
    env:
      SECRET_KEY: "dummy-testing-secret-key"
      ALGORITHM: "HS256"
        # DB_URL: "sqlite:///./test.db" # Add any other vars your app absolutely requires

    steps:
      - name: Checkout Code
      uses: actions/checkout@v4

      - name: Set up Python 3.12
      uses: actions/setup-python@v5
          with:
            python-version: '3.12.3'

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            cd backend
            pip install -r requirements.txt

        - name: Run Pytest
          run: |
            cd backend
            pytest -v


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "CI Tests Passed! Deploying to EC2..."
            
            cd /home/ubuntu/ChatApp
            chmod +x deploy.sh
            ./deploy.sh