# version: '3.8'

services:
  ping-main:
    image: 015903983337.dkr.ecr.ap-south-1.amazonaws.com/ping-main:1.5
    container_name: ping-main
    ports:
      - "8000:8000"
      - "50050:50050"
    env_file:
      - .env
    environment:
      - SERVICE_ADVERTISE_HOST=${HOST_IP}
      - SERVICE_GRPC_PORT=50050
      - SERVICE_HTTP_PORT=8000
      - 'CONNECT_ARGS={"statement_cache_size": 0, "prepared_statement_cache_size": 0}'
      - ALGORITHM=HS256
    ulimits:
      nofile: # To avoid "no file descriptors available" error. By default this will be 1024, for viretual env of docker.
        soft: 65536
        hard: 65536
    depends_on:
      - pgbouncer

  ping-cm:
    image: 015903983337.dkr.ecr.ap-south-1.amazonaws.com/ping-cm:1.4
    container_name: ping-cm
    ports:
      - "8001:8001"
      - "50051:50051"
    env_file:
      - .env
    environment:
      - SERVICE_ADVERTISE_HOST=${HOST_IP}
      - SERVICE_GRPC_PORT=50051
      - SERVICE_HTTP_PORT=8001
      - ALGORITHM=HS256
    depends_on:
      - ping-main

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    env_file:
      - .env
    environment:
    - POOL_MODE=transaction
    - MAX_CLIENT_CONN=50000          # Higher than your expected peak concurrency
    - DEFAULT_POOL_SIZE=100          # Adjust based on your Postgres max_connections
    - MIN_POOL_SIZE=10
    - RESERVE_POOL_SIZE=20
    - RESERVE_POOL_TIMEOUT=5
    - MAX_DB_CONNECTIONS=0           # or set based on Postgres capacity
    - ADMIN_USERS=postgres
    ulimits:
      nofile:
        soft: 131072
        hard: 131072
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro # ro = read-only
      - ./userlist.txt:/etc/pgbouncer/userlist.txt:ro

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ../frontend/dist:/usr/share/nginx/html:ro

  # nginx with static serving and Load Balancing
  ping-gateway:
    # image: ______
    container_name: ping-gateway
    ports:
      - "80:80"
    environment:
      - REDIS_URL=${REDIS_URL}
      - NGINX_CONF_PATH=/etc/nginx/conf.d/default.conf
    restart: unless-stopped